
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nyc_analytics_acreary'
version: '1.0.0'
config-version: 2
# Some default settings for dbt
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

# Set up models, which are basically SQL files, to create tables
models:
  nyc_analytics_acreary:

    assignment_work:

      staging:
        +materialized: view
        +schema: nyc_hw3_raw_data

      marts:
        +materialized: table
        +schema: nyc_hw3_raw_data

    project_work:

      staging:
        +materialized: view
        +schema: group_nine_final_proj

      marts:
        +materialized: table
        +schema: group_nine_final_proj

      conformed:
        +materialized: table
        +schema: group_nine_final_proj