
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nyc_analytics_acreary'
version: '1.0.0'
config-version: 2
# Some default settings for dbt
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

# Set up models, which are basically SQL files, to create tables
models:
 nyc_analytics_acreary:
   +materialized: table

   assignment_work:
     staging:
       +materialized: table
       +schema: nyc_transit_restaurants_staging

     marts:
       +materialized: table
       +schema: nyc_transit_restaurants_marts
      
       shared:
         +materialized: table

       source_nyc_open_restaurant_apps:
         +materialized: table

       nyc_hw3_raw_data_source_dot_service_requests_history:
         +materialized: table
         
         project_work:
  staging:
    +materialized: table
    +schema: nyc_311_collisions_staging
  marts:
    +materialized: table
    +schema: nyc_311_collisions_marts
    conformed:
      +materialized: table
    nyc_dot_service_requests_history_copy:
      +materialized: table
    groupnine_finalproj_mvcollisions:
      +materialized: table